spring:
  datasource:
    data: classpath*:sql/testdata-*.sql
    schema: classpath*:sql/schema.sql

graphiql:
  enabled: true

services:
  productservice:
    url: localhost
    port: 8084
    username: monolithicservice_user
    password: monolithicservice_user_password
  customerservice:
    url: localhost
    port: 8084
    username: monolithicservice_user
    password: monolithicservice_user_password
  ecommerceService:
    url: localhost
    port: 8084
    username: monolithicservice_user
    password: monolithicservice_user_password

security:
  whitelist:
    - /graphiql
    - /vendor/graphiql/**