spring:
  datasource:
    data: classpath:users.sql

graphiql:
  enabled: true

services:
  productservice:
    url: localhost
    port: 8081
    username: productservice_user
    password: productservice_user_password
  customerservice:
    url: localhost
    port: 8082
    api-key-header: x-api-key
    api-key: supersecret
  ecommerceService:
    url: localhost
    port: 8083
    username: ecommerceservice_user
    password: ecommerceservice_user_password

security:
  whitelist:
    - /graphiql
    - /graphiql/**