spring:
  application:
    name: IntegrationService

server:
  port: 8080
  http2:
    enabled: true

graphql:
  tools:
    schema-location-pattern: "schemas/**/*.graphqls"

graphiql:
  enabled: false