spring:
  datasource:
    data: classpath*:sql/testdata-*.sql
    schema: classpath*:sql/schema.sql

graphiql:
  enabled: true

services:
  productservice:
    authentication-type: BASIC_AUTH
    url: localhost
    port: 8084
    username: monolithicservice_admin
    password: monolithicservice_admin_password
  customerservice:
    authentication-type: BASIC_AUTH
    url: localhost
    port: 8084
    username: monolithicservice_admin
    password: monolithicservice_admin_password
  ecommerceService:
    authentication-type: BASIC_AUTH
    url: localhost
    port: 8084
    username: monolithicservice_admin
    password: monolithicservice_admin_password

security:
  whitelist:
    - /graphiql
    - /vendor/graphiql/**
    - /voyager
    - /vendor/voyager/**