graphiql:
  enabled: true

services:
  productservice:
    url: localhost
    port: 8081
    username: admin
    password: adminPassword
  customerservice:
    url: localhost
    port: 8082
    api-key-header: x-api-key
    api-key: supersecret
  ecommerceService:
    url: localhost
    port: 8083
    username: admin
    password: adminPassword

security:
  whitelist:
    - /h2-console/**
    - /graphiql