spring:
  application:
    name: IntegrationService

server:
  port: 8080
  http2:
    enabled: true

graphql:
  tools:
    schema-location-pattern: "schemas/**/*.graphqls"
  servlet:
    maxQueryDepth: 20
    #maxQueryComplexity: 10

graphiql:
  enabled: false

voyager:
  enabled: false

services:
  productservice:
    url: ${PRODUCTSERVICE_URL}
    port: ${PRODUCTSERVICE_PORT}
    username: ${PRODUCTSERVICE_USERNAME}
    password: ${PRODUCTSERVICE_USERNAME}
  customerservice:
    url: ${CUSTOMERSERVICE_URL}
    port: ${CUSTOMERSERVICE_PORT}
    api-key-header: x-api-key
    api-key: ${CUSTOMERSERVICE_API_KEY}
  ecommerceService:
    url: ${ECOMOMERCESERVICE_URL}
    port: ${ECOMMERCESERVICE_PORT}
    username: ${ECOMMERCESERVICE_USERNAME}
    password: ${ECOMMERCESERVICE_USERNAME}

logging:
  level:
    graphql.kickstart: debug