spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    #data: classpath*:sql/testdata.sql
    #schema: classpath*:sql/schema.sql
  resources:
    add-mappings: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: warn

springfox:
  documentation:
    swagger:
      v2:
        path: swagger

service:
  url: localhost
  port: 8080
  endpoint: /graphql
  username: integrationservice_user
  password: integrationservice_user_password
