spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    schema: classpath*:sql/schema.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  web:
    resources:
      add-mappings: true

logging:
  level:
    org.hibernate.SQL: warn
    at.technikum: debug

springfox:
  documentation:
    swagger:
      v2:
        path: swagger

service:
  url: localhost
  port: 8080
  endpoint: /graphql
  username: integrationservice_user
  password: integrationservice_user_password
