server:
  port: 8084
  http2:
    enabled: true

spring:
  application:
    name: monolithicService
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
  resources:
    add-mappings: true