spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    data: classpath*:sql/testdata.sql
    schema: classpath*:sql/schema.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  web:
    resources:
      add-mappings: true

logging:
  level:
    org.hibernate.SQL: warn

springfox:
  documentation:
    swagger:
      v2:
        path: swagger

security:
  whitelist:
    - /h2-console/**
    - /swagger

service:
  delay:
    enable-endpoint-delays: true
    enable-service-delays: true
    service-delay-mean: 0
    service-delay-standard-deviation: 0
    log-delays: true

customerservice:
  api-key:
    header: x-api-key
    values:
      - supersecret
      - megasecret
      - toptoptopsecret