spring:
  h2:
    console:
      enabled: true
      settings:
        trace: true

service:
  delay:
    enable-endpoint-delays: true
    enable-service-delays: true
    service-delay-mean: 100
    service-delay-standard-deviation: 100
    log-delays: true