
-- Default Products
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);
INSERT INTO product (name, description, weight, width, height, depth) VALUES ('Foo', 'Bar', 3.5, 3, 4, 5);

-- Default product reviews
INSERT INTO product_review (customer_id, product_id, stars, review) VALUES (1, 1, 1, 'bad');
INSERT INTO product_review (customer_id, product_id, stars, review) VALUES (2, 1, 3, 'meh');
INSERT INTO product_review (customer_id, product_id, stars, review) VALUES (3, 1, 5, 'good');
INSERT INTO product_review (customer_id, product_id, stars, review) VALUES (1, 2, 5, 'superb');